export var SAGA_FETCH_PROJECTS  = "SAGA_FETCH_PROJECTS";
export var SET_FETCH_PROJECTS   = "SET_FETCH_PROJECTS";

export var SAGA_FETCH_TOP_LIKED_PROJECTS = "SAGA_FETCH_TOP_LIKED_PROJECTS"
export var SET_FETCHED_TOP_LIKED_PROJECTS = "SET_FETCHED_TOP_LIKED_PROJECTS"

export var SAGA_FETCH_FEATURED_CATEGORY_PROJECTS = "SAGA_FETCH_FEATURED_CATEGORY_PROJECTS"
export var SET_FETCHED_FEATURED_CATEGORY_PROJECTS = "SET_FETCHED_FEATURED_CATEGORY_PROJECTS"