export var SAGA_FETCH_PROJECTS  = "SAGA_FETCH_PROJECTS";
export var SET_FETCH_PROJECTS   = "SET_FETCH_PROJECTS";

export var SAGA_FETCH_TOP_LIKED_PROJECTS = "SAGA_FETCH_TOP_LIKED_PROJECTS"
export var SET_FETCHED_TOP_LIKED_PROJECTS = "SET_FETCHED_TOP_LIKED_PROJECTS"

export var SAGA_FETCH_FEATURED_CATEGORY_PROJECTS = "SAGA_FETCH_FEATURED_CATEGORY_PROJECTS"
export var SET_FETCHED_FEATURED_CATEGORY_PROJECTS = "SET_FETCHED_FEATURED_CATEGORY_PROJECTS"

export var CLEAR_PROJECTS_STATE = "CLEAR_PROJECTS_STATE"
export var CLEAR_FEATURED_STATE = "CLEAR_FEATURED_STATE"
export var CLEAR_TOP_LIKED_STATE = "CLEAR_TOP_LIKED_STATE"

export var SAGA_REGISTER_USER_DETAILS_THIRD_PARTY_LOGIN = "SAGA_REGISTER_USER_DETAILS_THIRD_PARTY_LOGIN"
export var CHANGE_USER_STATE = "CHANGE_USER_STATE"
export var SET_USER_DETAILS = "SET_USER_DETAILS"
